/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editores;

import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Frame.DEFAULT_CURSOR;
import static java.awt.Frame.HAND_CURSOR;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import login_sql.DBManager_login;
import login_sql.add_animal;

/**
 *
 * @author nuria
 */
public class editar_cuidador extends javax.swing.JFrame {

    /**
     * Creates new form editar_cuidador
     */
    public editar_cuidador(int id_persona,String nombre,String apellidos,String telefono,String cargo,String salario) {
        initComponents();
        jtid_persona.setText(String.valueOf(id_persona));
    
        jtnombreCuidador2.setText(nombre);
        jtapelillodosCuidador.setText(apellidos);
        jtcuidadosTelefono.setText(telefono);
        jtcuidadosSalario.setText(salario);
        ListarEspecialidad();
         
    }
    
    //____________________________________________________________________________________________
    //______________________________________________________________________________________________________
    // LISTAR ESPECIES
    public void ListarEspecialidad() {

        String consulta_sql = " SELECT * FROM especialidad";

        ResultSet resultado = DBManager_login.obtener_tablas(DEFAULT_CURSOR, DISPOSE_ON_CLOSE, consulta_sql);
        // guardas en resultado en esta variable y el default te pone por defecto un 0
        try {
            while (resultado.next()) {
                String nombre_especialidad = resultado.getString("nombre");
                jcomboespecialidad.addItem(nombre_especialidad);
            }
        } catch (SQLException ex) {
            Logger.getLogger(add_animal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            resultado.close();
        } catch (SQLException ex) {
            Logger.getLogger(add_animal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capa0 = new javax.swing.JPanel();
        jtapelillodosCuidador1 = new javax.swing.JTextField();
        jtnombreCuidador1 = new javax.swing.JTextField();
        jtcuidadosCuidador1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2cargo = new javax.swing.JLabel();
        jtid_persona = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtapelillodosCuidador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtcuidadosSalario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcomboespecialidad = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtcuidadosTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtnombreCuidador2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel2cargo1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        capa0.setBackground(new java.awt.Color(255, 255, 255));
        capa0.setForeground(new java.awt.Color(255, 255, 255));
        capa0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtapelillodosCuidador1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtapelillodosCuidador1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtapelillodosCuidador1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtapelillodosCuidador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jtnombreCuidador1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtnombreCuidador1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtnombreCuidador1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtnombreCuidador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jtcuidadosCuidador1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtcuidadosCuidador1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtcuidadosCuidador1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtcuidadosCuidador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/Los-10-arboles-mas-grandes-del-mundo.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        capa0.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Slab", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar cuidador");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        capa0.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 240, 70));

        jLabel2cargo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2cargo.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2cargo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2cargo.setText("Id");
        capa0.add(jLabel2cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 79, -1));

        jtid_persona.setEditable(false);
        jtid_persona.setBackground(new java.awt.Color(255, 255, 255));
        jtid_persona.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtid_persona.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtid_persona.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtid_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 185, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Apellidos");
        capa0.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 79, -1));

        jtapelillodosCuidador.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtapelillodosCuidador.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtapelillodosCuidador.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtapelillodosCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 185, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Teléfono");
        capa0.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 119, -1));

        jtcuidadosSalario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtcuidadosSalario.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtcuidadosSalario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtcuidadosSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 185, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Especialidad ");
        capa0.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 119, -1));

        jcomboespecialidad.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jcomboespecialidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jcomboespecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboespecialidadActionPerformed(evt);
            }
        });
        capa0.add(jcomboespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 185, -1));

        jButton3.setText("Guardar");
        jButton3.setBackground(new java.awt.Color(102, 153, 0));
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        capa0.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 140, 50));

        jButton1.setText("Limpiar");
        jButton1.setBackground(new java.awt.Color(102, 153, 0));
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        capa0.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 140, 50));
        capa0.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Salario");
        capa0.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        jtcuidadosTelefono.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtcuidadosTelefono.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtcuidadosTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtcuidadosTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 185, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Nombre");
        capa0.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 79, -1));

        jtnombreCuidador2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtnombreCuidador2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtnombreCuidador2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtnombreCuidador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 185, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/Captura (1).png"))); // NOI18N
        capa0.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel2cargo1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2cargo1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2cargo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2cargo1.setText("Cargo");
        capa0.add(jLabel2cargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 79, -1));

        jComboBox1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));
        capa0.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capa0, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(capa0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboespecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboespecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboespecialidadActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // añadir especialidad a la tabla
       
        String nombre = jtnombreCuidador2.getText();
        String apellidos = jtapelillodosCuidador.getText();
        String cargo = jComboBox1.getSelectedItem().toString();

        // controlar campos
        if (nombre.equals("") || apellidos.equals("") || jtcuidadosTelefono.getText().equals("") || cargo.equals("") || jtcuidadosSalario.getText().equals("") || jcomboespecialidad.getSelectedItem().equals(null)) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios.");

        } else {
           int id = Integer.parseInt(jtid_persona.getText());
            int telefono = Integer.parseInt(jtcuidadosTelefono.getText());
            float salario = Float.parseFloat(jtcuidadosSalario.getText());

            boolean comprobar = DBManager_login.actualizar_persona(id,nombre, apellidos, telefono, cargo, salario);
            if (comprobar) {
                JOptionPane.showMessageDialog(null, "Añadido correctamente");

            } else {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
        }
         dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // limpiar cajas de texto
        jtapelillodosCuidador.setText("");
        jtcuidadosSalario.setText("");
        jtid_persona.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
           // Encima
        jButton3.setBackground(new Color(153, 153, 0));
        jButton3.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
           // Encima
        jButton1.setBackground(new Color(153, 153, 0));
        jButton1.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // fuera
        jButton1.setBackground(new Color(102, 153, 0));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
         // fuera
        jButton3.setBackground(new Color(102, 153, 0));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(editar_cuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(editar_cuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(editar_cuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(editar_cuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new editar_cuidador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel capa0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2cargo;
    private javax.swing.JLabel jLabel2cargo1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcomboespecialidad;
    private javax.swing.JTextField jtapelillodosCuidador;
    private javax.swing.JTextField jtapelillodosCuidador1;
    private javax.swing.JTextField jtcuidadosCuidador1;
    private javax.swing.JTextField jtcuidadosSalario;
    private javax.swing.JTextField jtcuidadosTelefono;
    private javax.swing.JTextField jtid_persona;
    private javax.swing.JTextField jtnombreCuidador1;
    private javax.swing.JTextField jtnombreCuidador2;
    // End of variables declaration//GEN-END:variables
}
