/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_sql;

import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import javax.swing.JOptionPane;
import metodos.TextPrompt;

/**
 *
 * @author nuria
 */
public class add_especialidad extends javax.swing.JFrame {

    /**
     * Creates new form add_especialidad
     */
    public add_especialidad() {
        initComponents();
        
        // Poner ejemplos en los text field
        TextPrompt placeholder = new TextPrompt ("Nueva Especialidad",jTextEspecialidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capa0 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabeladdEspecialidad = new javax.swing.JLabel();
        jTextEspecialidad = new javax.swing.JTextField();
        botonGuardarEspecialidad = new javax.swing.JButton();
        botonLimpiarEspecialidad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        capa0.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir Especialidad");

        jLabeladdEspecialidad.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabeladdEspecialidad.setForeground(new java.awt.Color(0, 153, 0));
        jLabeladdEspecialidad.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabeladdEspecialidad.setText("Nombre Especialidad");

        jTextEspecialidad.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jTextEspecialidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));

        botonGuardarEspecialidad.setBackground(new java.awt.Color(102, 153, 0));
        botonGuardarEspecialidad.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        botonGuardarEspecialidad.setText("Aceptar");
        botonGuardarEspecialidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonGuardarEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarEspecialidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarEspecialidadMouseExited(evt);
            }
        });
        botonGuardarEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarEspecialidadActionPerformed(evt);
            }
        });

        botonLimpiarEspecialidad.setBackground(new java.awt.Color(102, 153, 0));
        botonLimpiarEspecialidad.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        botonLimpiarEspecialidad.setText("Limpiar");
        botonLimpiarEspecialidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLimpiarEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonLimpiarEspecialidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonLimpiarEspecialidadMouseExited(evt);
            }
        });
        botonLimpiarEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarEspecialidadActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/Los-10-arboles-mas-grandes-del-mundo.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/Captura (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout capa0Layout = new javax.swing.GroupLayout(capa0);
        capa0.setLayout(capa0Layout);
        capa0Layout.setHorizontalGroup(
            capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capa0Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(capa0Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabeladdEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83))
                    .addGroup(capa0Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGuardarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(botonLimpiarEspecialidad)
                        .addGap(69, 69, 69))))
        );

        capa0Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonGuardarEspecialidad, botonLimpiarEspecialidad});

        capa0Layout.setVerticalGroup(
            capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capa0Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jLabeladdEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jTextEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(capa0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiarEspecialidad)
                    .addComponent(botonGuardarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        capa0Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonGuardarEspecialidad, botonLimpiarEspecialidad});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capa0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capa0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarEspecialidadActionPerformed
        if (!metodos.Utilidades_Control.contieneSoloLetras(jTextEspecialidad.getText())) {
            JOptionPane.showMessageDialog(null, "Solo se pueden introducir letras");

        } else {
            String especialidad = jTextEspecialidad.getText();

            boolean comprobar = DBManager_login.add_especialidad(especialidad);
            if (comprobar) {
                JOptionPane.showMessageDialog(null, "Se ha añadido correctamente");
                dispose();

            } else {
                JOptionPane.showMessageDialog(null, "No se ha añadido correctamente");

            }

        }


    }//GEN-LAST:event_botonGuardarEspecialidadActionPerformed

    private void botonLimpiarEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarEspecialidadActionPerformed

        jTextEspecialidad.setText("");


    }//GEN-LAST:event_botonLimpiarEspecialidadActionPerformed

    private void botonGuardarEspecialidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarEspecialidadMouseEntered
         // Encima
        botonGuardarEspecialidad.setBackground(new Color(153, 153, 0));
        botonGuardarEspecialidad.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonGuardarEspecialidadMouseEntered

    private void botonGuardarEspecialidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarEspecialidadMouseExited
           // fuera
        botonGuardarEspecialidad.setBackground(new Color(102, 153, 0));
    }//GEN-LAST:event_botonGuardarEspecialidadMouseExited

    private void botonLimpiarEspecialidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLimpiarEspecialidadMouseEntered
           // Encima
        botonLimpiarEspecialidad.setBackground(new Color(153, 153, 0));
        botonLimpiarEspecialidad.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonLimpiarEspecialidadMouseEntered

    private void botonLimpiarEspecialidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLimpiarEspecialidadMouseExited
           // fuera
        botonLimpiarEspecialidad.setBackground(new Color(102, 153, 0));
    }//GEN-LAST:event_botonLimpiarEspecialidadMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(add_especialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(add_especialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(add_especialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(add_especialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new add_especialidad().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarEspecialidad;
    private javax.swing.JButton botonLimpiarEspecialidad;
    private javax.swing.JPanel capa0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabeladdEspecialidad;
    private javax.swing.JTextField jTextEspecialidad;
    // End of variables declaration//GEN-END:variables
}
