/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_sql;

import editores.editar_cuidador;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import static java.awt.Frame.DEFAULT_CURSOR;
import static java.awt.Frame.HAND_CURSOR;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import metodos.TextPrompt;
import metodos.Utilidades_Control;

/**
 *
 * @author nuria
 */
public class add_cuidadores extends javax.swing.JFrame {

    /**
     * Creates new form add_cuidadores
     */
    public add_cuidadores() {
        initComponents();
        ListarEspecialidad();
        rellenar_tabla_cuidadores();

        // formato de la tabla
        Font myFont2 = new Font("Roboto light", Font.BOLD, 18);

        jTablelistar_cuidadores.getTableHeader().setFont(myFont2);

        // Poner ejemplos en los text field
        TextPrompt placeholder1 = new TextPrompt("Nombre persona", jtnombreCuidador2);
        TextPrompt placeholder2 = new TextPrompt("Apellidos persona", jtapelillodosCuidador);
        TextPrompt placeholder3 = new TextPrompt("XXXXXXXXX", jtcuidadosTelefono);
        TextPrompt placeholder4 = new TextPrompt("Salario en € ", jtcuidadosSalario);
    }
    //______________________________________________________________________________________________________
    // rellenar tabla cuidadores

    public void rellenar_tabla_cuidadores() {
        String sql = "Select * from personas";
        try {
            ResultSet resultado = DBManager_login.obtener_tablas(DEFAULT_CURSOR, DISPOSE_ON_CLOSE, sql);
            while (resultado.next()) {
                int id_persona = resultado.getInt("id_persona");
                String nombre = resultado.getString("nombre");
                String apellidos = resultado.getString("apellidos");
                String telefono = resultado.getString("telefono");
                String cargo = resultado.getString("cargo");
                String salario = resultado.getString("salario");

                DefaultTableModel model = (DefaultTableModel) jTablelistar_cuidadores.getModel();
                Object[] row = {id_persona, nombre, apellidos, telefono, cargo, salario};
                model.addRow(row);
            }
            resultado.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    //___________________________________________________________________________________________________
    // Vaciar tabla animales para no duplicar datos 
    public void vaciar_tablas() {

        //vaciamos la tabla recorriendola con un bucle for
        DefaultTableModel tb = (DefaultTableModel) jTablelistar_cuidadores.getModel();
        int a = jTablelistar_cuidadores.getRowCount() - 1; //contamos las filas
        //bucle para borrar todas las filas
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }

    }

//______________________________________________________________________________________________________
    // LISTAR ESPECIES
    public void ListarEspecialidad() {

        String consulta_sql = " SELECT * FROM especialidad";

        ResultSet resultado = DBManager_login.obtener_tablas(DEFAULT_CURSOR, DISPOSE_ON_CLOSE, consulta_sql);
        // guardas en resultado en esta variable y el default te pone por defecto un 0
        try {
            while (resultado.next()) {
                String nombre_especialidad = resultado.getString("nombre");
                jcomboespecialidad.addItem(nombre_especialidad);
            }
        } catch (SQLException ex) {
            Logger.getLogger(add_animal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            resultado.close();
        } catch (SQLException ex) {
            Logger.getLogger(add_animal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameListar_cuidadores = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablelistar_cuidadores = new javax.swing.JTable();
        jButtonModificar_cuidador = new javax.swing.JButton();
        jButtonBorrar_cuidador = new javax.swing.JButton();
        capa0 = new javax.swing.JPanel();
        jtapelillodosCuidador1 = new javax.swing.JTextField();
        jtnombreCuidador1 = new javax.swing.JTextField();
        jtcuidadosCuidador1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2cargo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtapelillodosCuidador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtcuidadosSalario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcomboespecialidad = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtcuidadosTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtnombreCuidador2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jFrameListar_cuidadores.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrameListar_cuidadores.setLocation(new java.awt.Point(480, 300));
        jFrameListar_cuidadores.setMinimumSize(new java.awt.Dimension(606, 420));
        jFrameListar_cuidadores.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                jFrameListar_cuidadoresWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel10.setText("Listar Cuidadores");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jTablelistar_cuidadores.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jTablelistar_cuidadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_persona", "Nombre", "Apellidos", "Telefono", "Cargo", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablelistar_cuidadores);
        if (jTablelistar_cuidadores.getColumnModel().getColumnCount() > 0) {
            jTablelistar_cuidadores.getColumnModel().getColumn(0).setResizable(false);
            jTablelistar_cuidadores.getColumnModel().getColumn(1).setResizable(false);
            jTablelistar_cuidadores.getColumnModel().getColumn(2).setResizable(false);
            jTablelistar_cuidadores.getColumnModel().getColumn(3).setResizable(false);
            jTablelistar_cuidadores.getColumnModel().getColumn(4).setResizable(false);
        }

        jButtonModificar_cuidador.setBackground(new java.awt.Color(255, 204, 0));
        jButtonModificar_cuidador.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jButtonModificar_cuidador.setText("Modificar");
        jButtonModificar_cuidador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonModificar_cuidador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonModificar_cuidadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonModificar_cuidadorMouseExited(evt);
            }
        });
        jButtonModificar_cuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificar_cuidadorActionPerformed(evt);
            }
        });

        jButtonBorrar_cuidador.setBackground(new java.awt.Color(204, 0, 0));
        jButtonBorrar_cuidador.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jButtonBorrar_cuidador.setText("Borrar");
        jButtonBorrar_cuidador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBorrar_cuidador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBorrar_cuidadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonBorrar_cuidadorMouseExited(evt);
            }
        });
        jButtonBorrar_cuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrar_cuidadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButtonModificar_cuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButtonBorrar_cuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar_cuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrar_cuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonBorrar_cuidador, jButtonModificar_cuidador});

        javax.swing.GroupLayout jFrameListar_cuidadoresLayout = new javax.swing.GroupLayout(jFrameListar_cuidadores.getContentPane());
        jFrameListar_cuidadores.getContentPane().setLayout(jFrameListar_cuidadoresLayout);
        jFrameListar_cuidadoresLayout.setHorizontalGroup(
            jFrameListar_cuidadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameListar_cuidadoresLayout.setVerticalGroup(
            jFrameListar_cuidadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        capa0.setBackground(new java.awt.Color(255, 255, 255));
        capa0.setForeground(new java.awt.Color(255, 255, 255));
        capa0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtapelillodosCuidador1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtapelillodosCuidador1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtapelillodosCuidador1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtapelillodosCuidador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jtnombreCuidador1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtnombreCuidador1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtnombreCuidador1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtnombreCuidador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jtcuidadosCuidador1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtcuidadosCuidador1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtcuidadosCuidador1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtcuidadosCuidador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/Los-10-arboles-mas-grandes-del-mundo.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        capa0.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Slab", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir Empleados");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        capa0.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 240, 70));

        jLabel2cargo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2cargo.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2cargo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2cargo.setText("Cargo");
        capa0.add(jLabel2cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 79, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Apellidos");
        capa0.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 79, -1));

        jtapelillodosCuidador.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtapelillodosCuidador.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtapelillodosCuidador.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtapelillodosCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 185, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Teléfono");
        capa0.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 119, -1));

        jtcuidadosSalario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtcuidadosSalario.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtcuidadosSalario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtcuidadosSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 185, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Especialidad ");
        capa0.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 119, -1));

        jcomboespecialidad.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jcomboespecialidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jcomboespecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboespecialidadActionPerformed(evt);
            }
        });
        capa0.add(jcomboespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 185, -1));

        jButton3.setBackground(new java.awt.Color(102, 153, 0));
        jButton3.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jButton3.setText("Aceptar");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        capa0.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 130, 40));

        jButton1.setBackground(new java.awt.Color(102, 153, 0));
        jButton1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        capa0.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 130, 40));
        capa0.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Salario");
        capa0.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        jtcuidadosTelefono.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtcuidadosTelefono.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtcuidadosTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtcuidadosTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 185, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Nombre");
        capa0.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 79, -1));

        jtnombreCuidador2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jtnombreCuidador2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtnombreCuidador2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 0)));
        capa0.add(jtnombreCuidador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 185, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/Captura (1).png"))); // NOI18N
        capa0.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 153, 0));
        jButton2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jButton2.setText("Listar Empleados");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        capa0.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 260, 50));

        jComboBox1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));
        capa0.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capa0, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(capa0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboespecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboespecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboespecialidadActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // añadir especialidad a la tabla
        String nombre = jtnombreCuidador2.getText();
        String apellidos = jtapelillodosCuidador.getText();
        String cargo = jComboBox1.getSelectedItem().toString();

        // controlar campos
        if (nombre.equals("") || apellidos.equals("") || jtcuidadosTelefono.getText().equals("") || cargo.equals("") || jtcuidadosSalario.getText().equals("") || jcomboespecialidad.getSelectedItem().equals(null)) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios.");

        } else {
            float salario = Float.parseFloat(jtcuidadosSalario.getText());
            int telefono = Integer.parseInt(jtcuidadosTelefono.getText());
            if (!Utilidades_Control.contieneSoloNumeros(String.valueOf(telefono))) {
                JOptionPane.showMessageDialog(null, "Este campo solo acepta caracteres numericos");
                jtcuidadosTelefono.setText("");
            } else if (!Utilidades_Control.contieneSoloNumeros(String.valueOf(salario))) {
                JOptionPane.showMessageDialog(null, "Este campo solo acepta caracteres numericos");
                jtcuidadosSalario.setText("");

            }

            boolean comprobar = DBManager_login.add_cuidadores(nombre, apellidos, telefono, cargo, salario);
            if (comprobar) {
                JOptionPane.showMessageDialog(null, "Añadido correctamente");

            } else {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // limpiar cajas de texto
        jtapelillodosCuidador.setText("");
        jtcuidadosSalario.setText("");

        jtnombreCuidador2.setText("");
        jtcuidadosTelefono.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // llama listar cuidador
        jFrameListar_cuidadores.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonBorrar_cuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrar_cuidadorActionPerformed

        // BOTON BORRAR persona DE LA LISTA
        int fila = jTablelistar_cuidadores.getSelectedRow();// coge la fila que has selecionado 
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha selecionado ninguna fila");

        } else {
            int id = (int) jTablelistar_cuidadores.getValueAt(fila, 0);
            DBManager_login.borrar_persona(id);

        }
    }//GEN-LAST:event_jButtonBorrar_cuidadorActionPerformed

    private void jFrameListar_cuidadoresWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameListar_cuidadoresWindowGainedFocus
        // actualizar tabla
        vaciar_tablas();
        rellenar_tabla_cuidadores();
    }//GEN-LAST:event_jFrameListar_cuidadoresWindowGainedFocus

    private void jButtonModificar_cuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificar_cuidadorActionPerformed
        // editar cuidadores
        int fila = jTablelistar_cuidadores.getSelectedRow();// coge la fila que has selecionado 
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha selecionado ninguna fila");

        } else {
            int id_persona = (int) jTablelistar_cuidadores.getValueAt(fila, 0);// este coje la columna 0 que es la del id
            String nombre = (String) jTablelistar_cuidadores.getValueAt(fila, 1);
            String apellidos = (String) jTablelistar_cuidadores.getValueAt(fila, 2);
            String telefono = (String) jTablelistar_cuidadores.getValueAt(fila, 3);
            String cargo = (String) jTablelistar_cuidadores.getValueAt(fila, 4);
            String salario = (String) jTablelistar_cuidadores.getValueAt(fila, 5);
            editores.editar_cuidador open = new editores.editar_cuidador(id_persona, nombre, apellidos, telefono, cargo, salario);
            open.setVisible(true);

// actualizar tabla
            vaciar_tablas();
            rellenar_tabla_cuidadores();
        }
    }//GEN-LAST:event_jButtonModificar_cuidadorActionPerformed

    private void jButtonModificar_cuidadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificar_cuidadorMouseEntered
        // Encima
        jButtonModificar_cuidador.setBackground(new Color(255, 148, 14));
        jButtonModificar_cuidador.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButtonModificar_cuidadorMouseEntered

    private void jButtonModificar_cuidadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificar_cuidadorMouseExited
        // fuera
        jButtonModificar_cuidador.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_jButtonModificar_cuidadorMouseExited

    private void jButtonBorrar_cuidadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrar_cuidadorMouseEntered
        // encima
        jButtonBorrar_cuidador.setBackground(new Color(233, 71, 68));
        jButtonBorrar_cuidador.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButtonBorrar_cuidadorMouseEntered

    private void jButtonBorrar_cuidadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrar_cuidadorMouseExited
        // fuera
        jButtonBorrar_cuidador.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_jButtonBorrar_cuidadorMouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // Encima
        jButton2.setBackground(new Color(153, 153, 0));
        jButton2.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // fuera
        jButton2.setBackground(new Color(102, 153, 0));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
           // Encima
        jButton3.setBackground(new Color(153, 153, 0));
        jButton3.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
         // fuera
        jButton3.setBackground(new Color(102, 153, 0));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
          // Encima
        jButton1.setBackground(new Color(153, 153, 0));
        jButton1.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
          // fuera
        jButton1.setBackground(new Color(102, 153, 0));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    //    public static void main(String args[]) {
    //        /* Set the Nimbus look and feel */
    //        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //         */
    //        try {
    //            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //                if ("Nimbus".equals(info.getName())) {
    //                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                    break;
    //                }
    //            }
    //        } catch (ClassNotFoundException ex) {
    //            java.util.logging.Logger.getLogger(add_cuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (InstantiationException ex) {
    //            java.util.logging.Logger.getLogger(add_cuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (IllegalAccessException ex) {
    //            java.util.logging.Logger.getLogger(add_cuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //            java.util.logging.Logger.getLogger(add_cuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        }
    //        //</editor-fold>
    //
    //        /* Create and display the form */
    //        java.awt.EventQueue.invokeLater(new Runnable() {
    //            public void run() {
    //                new add_cuidadores().setVisible(true);
    //            }
    //        });
    //    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel capa0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBorrar_cuidador;
    private javax.swing.JButton jButtonModificar_cuidador;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrameListar_cuidadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2cargo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablelistar_cuidadores;
    private javax.swing.JComboBox<String> jcomboespecialidad;
    private javax.swing.JTextField jtapelillodosCuidador;
    private javax.swing.JTextField jtapelillodosCuidador1;
    private javax.swing.JTextField jtcuidadosCuidador1;
    private javax.swing.JTextField jtcuidadosSalario;
    private javax.swing.JTextField jtcuidadosTelefono;
    private javax.swing.JTextField jtnombreCuidador1;
    private javax.swing.JTextField jtnombreCuidador2;
    // End of variables declaration//GEN-END:variables
}
