
package login_sql;

import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;

/**
 *
 * @author nuria
 */
public class panel_principal extends javax.swing.JFrame {

    /**
     * Creates new form panel_principal
     */
    public panel_principal() {
        initComponents();
    }
    
//    public void rellenar_tabla(){
//        String consulta=
//        ResulSet resultado = DBManager_login.obtener_tablas(PROPERTIES, DISPOSE_ON_CLOSE, consulta_sql)
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        botonTablaAnimal = new javax.swing.JButton();
        botonTablaAnimal1 = new javax.swing.JButton();
        botonTablaAnimal2 = new javax.swing.JButton();
        botonTablaAnimal3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1cerrarTabla(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel3.setText("Panel Principal");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        labelTitulo.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botonTablaAnimal.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        botonTablaAnimal.setText("Animales");
        botonTablaAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonTablaAnimalMouseEntered(evt);
            }
        });
        botonTablaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTablaAnimalActionPerformed(evt);
            }
        });

        botonTablaAnimal1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        botonTablaAnimal1.setText("Añadir Trabajos");
        botonTablaAnimal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonTablaAnimal1MouseEntered(evt);
            }
        });
        botonTablaAnimal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTablaAnimal1ActionPerformed(evt);
            }
        });

        botonTablaAnimal2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        botonTablaAnimal2.setText("Cuidadores");
        botonTablaAnimal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonTablaAnimal2MouseEntered(evt);
            }
        });
        botonTablaAnimal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTablaAnimal2ActionPerformed(evt);
            }
        });

        botonTablaAnimal3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        botonTablaAnimal3.setText("Añadir Especialidad");
        botonTablaAnimal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonTablaAnimal3MouseEntered(evt);
            }
        });
        botonTablaAnimal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTablaAnimal3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jButton1.setText("Tareas");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/baner2.jpg"))); // NOI18N

        jButton2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jButton2.setText("Añadir Especie");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonTablaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonTablaAnimal2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonTablaAnimal1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonTablaAnimal3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonTablaAnimal, botonTablaAnimal1, botonTablaAnimal2, botonTablaAnimal3, jButton1, jButton2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTablaAnimal1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTablaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTablaAnimal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTablaAnimal2)
                    .addComponent(jButton2))
                .addGap(64, 64, 64))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonTablaAnimal, botonTablaAnimal1, botonTablaAnimal2, botonTablaAnimal3, jButton1, jButton2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1cerrarTabla(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1cerrarTabla
        // cerrar tabla
        dispose();
    }//GEN-LAST:event_jLabel1cerrarTabla

    private void botonTablaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTablaAnimalActionPerformed
        // Boton animal
        add_animal open = new add_animal();
        open.setVisible(true);
    }//GEN-LAST:event_botonTablaAnimalActionPerformed

    private void botonTablaAnimal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTablaAnimal1ActionPerformed
        add_tipo_tarea open = new add_tipo_tarea();
        open.setVisible(true);
    }//GEN-LAST:event_botonTablaAnimal1ActionPerformed

    private void botonTablaAnimal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTablaAnimal2ActionPerformed
        //cuidadores
        add_cuidadores open = new  add_cuidadores();
        open.setVisible(true);
    }//GEN-LAST:event_botonTablaAnimal2ActionPerformed

    private void botonTablaAnimal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTablaAnimal3ActionPerformed
        // especialidad
        add_especialidad open = new   add_especialidad();
        open.setVisible(true);
    }//GEN-LAST:event_botonTablaAnimal3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //tareas
        add_tareas  open = new add_tareas();
        open.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // especie
        add_especie open = new add_especie();
        open.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
           jButton1.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButton1MouseEntered

    private void botonTablaAnimalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTablaAnimalMouseEntered
        botonTablaAnimal.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonTablaAnimalMouseEntered

    private void botonTablaAnimal2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTablaAnimal2MouseEntered
        botonTablaAnimal2.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonTablaAnimal2MouseEntered

    private void botonTablaAnimal1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTablaAnimal1MouseEntered
        botonTablaAnimal1.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonTablaAnimal1MouseEntered

    private void botonTablaAnimal3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTablaAnimal3MouseEntered
         botonTablaAnimal3.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonTablaAnimal3MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
         jButton2.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButton2MouseEntered

    /**
     * @param args the command line arguments
     */
//   s
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonTablaAnimal;
    private javax.swing.JButton botonTablaAnimal1;
    private javax.swing.JButton botonTablaAnimal2;
    private javax.swing.JButton botonTablaAnimal3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
